training:
  val_size: 0.0
  n_iter: 100
  eval_inter: 5
  folds: 5
  n_repeats: 5
  lr: 1.0e-3
  batch_size: 32

db_conformer:
  patch_size: 100
  spa_dim: 16
  gate_flag: False
  posemb_flag: True
  branch: 'all'
  chn_attn_flag: True
  fts_attn_flag: False
  emb_size: 40
  tem_depth: 2
  chn_depth: 2

mtf_c:
  patch_size: 100
  spa_dim: 16
  gate_flag: False
  posemb_flag: True
  branch: 'all'
  chn_attn_flag: False
  fts_attn_flag: True
  patch_emb_size: 40
  sst_emb_size: 40
  tem_depth: 2
  chn_depth: 2