BNCI2014_001:
  epoch_start: 0.5
  epoch_end: 3.5

BNCI2014_002:
  epoch_start: 0.5
  epoch_end: 3.5

BNCI2014_004:
  epoch_start: 0.5
  epoch_end: 3.5

BNCI2015_001:
  epoch_start: 0.5
  epoch_end: 3.5

BNCI2015_004:
  epoch_start: 0.5
  epoch_end: 3.5

AlexMI:
  epoch_start: 0.5
  epoch_end: 3.5

Liu2024:
  epoch_start: 0.5
  epoch_end: 3.5

Kalunga2016:
  epoch_start: 0.0
  epoch_end: null

Nakanishi2015:
  epoch_start: 0.0
  epoch_end: null

Wang2021Combined:
  epoch_start: 0.0
  epoch_end: null

MAMEM2:
  epoch_start: 0.0
  epoch_end: null

MAMEM3:
  epoch_start: 0.0
  epoch_end: null

Wang2016:
  epoch_start: 0.0
  epoch_end: null

Cattan2019_PHMD:
  epoch_start: 10.0
  epoch_end: 50.0

Rodrigues2017:
  epoch_start: 10.0
  epoch_end: 50.0

Hinss2021:
  epoch_start: 10.0
  epoch_end: 50.0