training:
  val_size: 0.0
  n_iter: 100
  eval_inter: 5
  lr: 1.0e-3
  batch_size: 32

db_conformer:
  patch_size: 100
  filter_banks: 11
  freq_downsample: 1
  wsize_divisor: 2
  spa_dim: 16
  gate_flag: False
  posemb_flag: True
  branch: 'all'
  chn_attn_flag: True
  fts_attn_flag: False
  sst_method: False
  stft_reconstruction: False
  emb_size: 40
  tem_depth: 1
  chn_depth: 1

mtf_c:
  patch_size: 100
  filter_banks: 11
  freq_downsample: 1
  wsize_divisor: 2
  spa_dim: 16
  gate_flag: False
  posemb_flag: True
  branch: 'f_t_s'  # Options: 'all', 'ft_s', 'fs_t', 'f_t_s', 'f_ts'
  chn_attn_flag: False
  fts_attn_flag: False
  sst_method: 'filter_banks'
  stft_reconstruction: 'frequency'
  ct_shared_projection: False  # Use shared projection in spectrogram estimator (filter_banks only)
  sst_shared_projection: False  # Project embeddings to SST dimension
  patch_emb_size: 40
  n_heads_patch: 4
  sst_emb_size: 40
  tem_depth: 1
  chn_depth: 1
