db_conformer:
  patch_size: 100
  spa_dim: 16
  gate_flag: False
  posemb_flag: True
  branch: 'all'
  chn_attn_flag: True
  emb_size: 40
  tem_depth: 2
  chn_depth: 2

mtf_c:
  patch_size: 100
  spa_dim: 16
  gate_flag: False
  posemb_flag: True
  chn_attn_flag: True
  patch_emb_size: 40
  tem_depth: 2
  chn_depth: 2
  spec_depth: 2

  sst_method: 'frequency_backbone'
  spectrum_attn_flag: True
  filter_banks: 11
  filter_banks_variant: 'MultiscaleTemporalCollapse_ChannelsExpand_FilterBanks'
  freq_downsample: 1
  wsize_divisor: 2
  temporal_kernel: 43