db_conformer: &db_conformer
  BNCI2014_001: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=BNCI2014_001
    | validation_strategy=loso/2026-08-10T12:28:44.005199|model:db_r_conformer
  BNCI2014_002: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=BNCI2014_002
    | validation_strategy=loso/2026-08-10T13:53:40.545587|model:db_r_conformer
  BNCI2014_004: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=BNCI2014_004
    | validation_strategy=loso/2026-08-10T15:51:03.576702|model:db_r_conformer
  Cattan2019_PHMD: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=Cattan2019_PHMD
    | validation_strategy=loso/2026-08-10T08:18:37.601140|model:db_r_conformer
  Kalunga2016: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=Kalunga2016
    | validation_strategy=loso/2026-08-10T10:26:03.680952|model:db_r_conformer
  Nakanishi2015: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=Nakanishi2015
    | validation_strategy=loso/2026-08-10T09:27:04.972240|model:db_r_conformer
  Rodrigues2017: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=Rodrigues2017
    | validation_strategy=loso/2026-08-10T08:46:25.057976|model:db_r_conformer
mtf_c: &mtf_c
  BNCI2014_001: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=BNCI2014_001
    | validation_strategy=loso/2026-08-11T16:00:30.057514|model:mtf_r_c
  BNCI2014_002: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=BNCI2014_002
    | validation_strategy=loso/2026-08-11T17:48:32.860746|model:mtf_r_c
  BNCI2014_004: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=BNCI2014_004
    | validation_strategy=loso/2026-08-11T18:53:53.273909|model:mtf_r_c
  Cattan2019_PHMD: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=Cattan2019_PHMD
    | validation_strategy=loso/2026-08-11T15:33:05.367105|model:mtf_r_c
  Kalunga2016: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=Kalunga2016
    | validation_strategy=loso/2026-08-11T17:36:11.790121|model:mtf_r_c
  Nakanishi2015: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=Nakanishi2015
    | validation_strategy=loso/2026-08-11T16:50:24.223617|model:mtf_r_c
  Rodrigues2017: experiments/sst_decoding+NRMSE_Loss+Loss_checkpointing/dataset=Rodrigues2017
    | validation_strategy=loso/2026-08-11T16:04:34.495210|model:mtf_r_c
db_r_conformer: *db_conformer
mtf_r_c: *mtf_c
mtf_tr_c: *mtf_c
